<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.p.LWX6S' shared service.

return $this->privates['.service_locator.p.LWX6S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'guestRepository' => ['privates', 'App\\Repository\\GuestRepository', 'getGuestRepositoryService.php', true],
]);
