<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\GuestAdminController::batchActionDelete' => ['privates', '.service_locator.ctFf6Xq', 'get_ServiceLocator_CtFf6XqService.php', true],
    'App\\Controller\\GuestController::delete' => ['privates', '.service_locator.sPQDuW1', 'get_ServiceLocator_SPQDuW1Service.php', true],
    'App\\Controller\\GuestController::edit' => ['privates', '.service_locator.sPQDuW1', 'get_ServiceLocator_SPQDuW1Service.php', true],
    'App\\Controller\\GuestController::index' => ['privates', '.service_locator.p.LWX6S', 'get_ServiceLocator_P_LWX6SService.php', true],
    'App\\Controller\\GuestController::show' => ['privates', '.service_locator.sPQDuW1', 'get_ServiceLocator_SPQDuW1Service.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\GuestAdminController:batchActionDelete' => ['privates', '.service_locator.ctFf6Xq', 'get_ServiceLocator_CtFf6XqService.php', true],
    'App\\Controller\\GuestController:delete' => ['privates', '.service_locator.sPQDuW1', 'get_ServiceLocator_SPQDuW1Service.php', true],
    'App\\Controller\\GuestController:edit' => ['privates', '.service_locator.sPQDuW1', 'get_ServiceLocator_SPQDuW1Service.php', true],
    'App\\Controller\\GuestController:index' => ['privates', '.service_locator.p.LWX6S', 'get_ServiceLocator_P_LWX6SService.php', true],
    'App\\Controller\\GuestController:show' => ['privates', '.service_locator.sPQDuW1', 'get_ServiceLocator_SPQDuW1Service.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
