<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ctFf6Xq' shared service.

return $this->privates['.service_locator.ctFf6Xq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'query' => ['privates', '.errored..service_locator.ctFf6Xq.Sonata\\AdminBundle\\Datagrid\\ProxyQueryInterface', NULL, 'Cannot autowire service ".service_locator.ctFf6Xq": it references interface "Sonata\\AdminBundle\\Datagrid\\ProxyQueryInterface" but no such service exists. Did you create a class that implements this interface?'],
]);
