<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.ctFf6Xq.Sonata\AdminBundle\Datagrid\ProxyQueryInterface' shared service.

include_once $this->targetDirs[3].'\\vendor\\sonata-project\\admin-bundle\\src\\Datagrid\\ProxyQueryInterface.php';

return $this->privates['.errored..service_locator.ctFf6Xq.Sonata\\AdminBundle\\Datagrid\\ProxyQueryInterface'] = new \Sonata\AdminBundle\Datagrid\ProxyQueryInterface();
