<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU51Cyta\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU51Cyta/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU51Cyta.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU51Cyta\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerU51Cyta\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'U51Cyta',
    'container.build_id' => '0c2edd43',
    'container.build_time' => 1557733290,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU51Cyta');
